POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "The WebSite 2",
    "author": "Ville Johannes Pajala",
    "url": "https://www.villejohannespajala.com",
    "likes": 333
}
